export const ApiEndpoints = {
    login: '/auth/login',
    Authentication: '/auth/secure',
    register: '/auth/register',
    usuarios: '/usuarios',
    RolesByUsuarioId: '/usuarioRoles/usuario/roles',
    AllUserRoles: '/usuarioRoles',
    general: '/general',
    forms: '/formularios',
    pharmacies: '/farmacias',
    licenses: '/licencias',
    provinces: '/provincias',
    sanctions: '/sanciones',
    inspections: '/inspecciones',
    requests: '/servicios',
    typesRequests: '/tipos-servicio',
  };