export const ApiEndpoints = {
    login: '/auth/login',
    Authentication: '/auth/secure',
    register: '/auth/register',
    usuarios: '/usuarios',
    uploadProfilePicture: '/usuarios/upload-profile-picture',
    RolesByUsuarioId: '/usuarioRoles/usuario/roles',
    getAllUsersByRolId: '/usuarioRoles/rol',
    AllUserRoles: '/usuarioRoles',
    general: '/general',
    forms: '/formularios',
    pharmacies: '/farmacias',
    licenses: '/licencias',
    provinces: '/provincias',
    sanctions: '/sanciones',
    inspections: '/inspecciones',
    requests: '/servicios',
    typesRequests: '/tipos-servicio',
    checklists: '/listas-verificacion',

  };